mysite/food/urls.py
from django.urls import path
from . import views

app_name = 'food'
urlpatterns = [
    # /food/
    path('',views.IndexClassView.as_view(),name='index'),
    # /food/item
    path('item/',views.item,name='item'),
    # /food/1
    path('<int:pk>/', views.FoodDetail.as_view(),name='detail'),
    # add items
    path('add/', views.CreateItem.as_view(), name='create_item'),
    # delete item
    path('delete/<int:id>', views.delete_item, name='delete_item'),
    # edit item
    path('edit/<int:id>/', views.edit_item, name='edit_item'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.profilePage, name='profile'),
]



urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Item(models.Model):

    def __str__(self):
        return self.item_name

    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500, default="http://via.placeholder.com/640x360")
    
    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk":self.pk})
    
        

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='profile_pictures', default ="user.jpg")
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

mysite/food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ["item_name", "item_desc", "item_price", "item_image"]
        

mysite/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email', 'password1', 'password2']

mysite/food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Item
from .forms import ItemForm
from django.template import loader
from django.views.generic.list import ListView 
from django.views.generic.detail import DetailView 
from django.views.generic.edit import CreateView

# Create your views here.
def index(request):
    item_list = Item.objects.all()
    context ={
        'item_list': item_list,
    }
    return render(request, 'food/index.html', context)  

class IndexClassView(ListView):
    model = Item;
    template_name = 'food/index.html'
    context_object_name = 'item_list'



def item(request):
    return HttpResponse('<h1>This is an item view</h1>')



def detail(request,item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        'item': item,
    }

    return render(request, 'food/detail.html', context)

class FoodDetail(DetailView):
    model = Item;
    template_name = 'food/detail.html'


# def create_item(request):
#     form = ItemForm(request.POST or None)

#     if form.is_valid():
#         form.save()
#         return redirect('food:index')
    
#     return render(request, 'food/item-form.html', {'form':form })   

class CreateItem(CreateView):
    model = Item;
    fields = ['item_name', 'item_desc', 'item_price', 'item_image']
    template_name = 'food/item-form.html'

    def form_valid(self, form):
        form.instance.user_name = self.request.user

        return super().form_valid(form)



def delete_item(request, id):
    item = Item.objects.get(id=id)

    context = {'item':item}

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    return render(request, 'food/delete-form.html', context)

def edit_item(request, id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request, 'food/edit-form.html', {'form':form, 'item':item })   

mysite/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import RegisterForm
from django.contrib import messages
# Create your views here.

def register(request):
    form = RegisterForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'welcome {username}, your account is created')
            return redirect('login')
    return render (request, 'users/register.html',{'form':form})

@login_required
def profilePage(request):
    return render(request, 'users/profile.html')

mysite/food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Document</title>

</head>
<body>
 
    <nav class="navbar navbar-dark bg-dark">
        <a href="{% url 'food:index' %}" class="navbar-brand">Food App</a>
        <div class="navbar">
            <a href="{% url 'food:index' %}" class="nav-item nav-link">Home</a>    
            {% if user.is_authenticated %}
                <a href="{% url 'food:create_item' %}" class="nav-item nav-link">Add Item</a>
                <a href="{% url 'profile' %}" class="nav-item nav-link">Profile</a>
                <a href="{% url 'logout' %}" class="nav-item nav-link">Logout</a>
            {% else %}
                <a href="{% url 'register' %}" class="nav-item nav-link">Register</a>    
                <a href="{% url 'login' %}" class="nav-item nav-link">Login</a>
            {% endif %}
        </div>
    </nav>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
    {% endif %}
    {% block body %}
    {% endblock %}


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

mysite/food/templates/food/delete-form.html
{% extends 'food/base.html' %}
{% block body %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header bg-danger text-white text-center">
                    <div class="card-title">
                        <h3>Confirm Delete</h3>
                    </div>
                </div>
                <div class="card-body">
                    <form  method="post">
                        {% csrf_token %}
                        <h2>Are you sure you want to delete {{ item.item_name }}</h2>
                        <a class="btn btn-secondary" href="{% url 'food:detail' item.id %}">Cancel</a>
                        <button type="submit" class="btn btn-danger">Confirm</button>
                    </form> 
                </div> 
            </div>          
        </div>
    </div>
</div>

{% endblock %}

mysite/food/templates/food/detail.html
{% extends 'food/base.html' %}
{% block body %}
 <div class="container">
     <div class="row mt-4">
         <div class="col-md-6">
            <img src="{{ item.item_image }}" height="250px" class="card" alt="">
         </div>
         <div class="col-md-6">
            <h1> {{ object.item_name}} </h1>
            <h2> {{ object.item_desc }} </h2>
            <h3> ${{ object.item_price }} </h3>
            <span>
            {% if user.is_authenticated %}
                <a href="{% url 'food:delete_item' item.id %}" class="btn btn-danger">Delete</a>
                <a href="{% url 'food:edit_item' item.id %}" class="btn btn-primary">Edit</a>
            {% else %}
                <a href="#" class="btn btn-danger disabled">Delete</a>
                <a href="#" class="btn btn-primary disabled">Edit</a>
            {% endif %}
            </span>
        </div>
     </div>
 </div>  
    


{% endblock %}

mysite/food/templates/food/edit-form.html
{% extends 'food/base.html' %}
{% block body %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header bg-info text-white text-center">
                    <div class="card-title">
                        <h3>Edit Item</h3>
                    </div>
                </div>
                <div class="card-body">
                    <form  method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.name }}
                                <br>
                                {{ field }}
                            </div>
                        {% endfor %}
                        <button class="btn btn-primary" type="submit">Save</button>
                    </form> 
                </div> 
            </div>          
        </div>
    </div>
</div>


{% endblock %}

mysite/food/templates/food/index.html
{% extends 'food/base.html' %}
{% block body %}
    {% for item in item_list %}

        <div class="row mt-4 mb-4">
            <div class="col-md-3 offset-md-2">
                <img class="card" height="150px" src="{{ item.item_image }}" alt="">
            </div>
            <div class="col-md-4">
                <h3>{{ item.item_name }}</h3>
                <h5>{{ item.item_desc }}</h5>
                <h5>${{ item.item_price }}</h6>
                <p>posted by: <strong>{{ item.user_name }}</strong></p>
            </div>
            <div class="col-md-2">
                <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
            </div>
        </div>

    {% endfor %}





<!-- Old Code 
    {% for item in item_list %}
        <ul>
            <li>
                <a href="{% url 'food:detail' item.id %}"> {{ item.id }}--{{ item.item_name }} </a>
            </li>
        </ul>
    {% endfor %} -->
{% endblock %}

mysite/food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header bg-info text-white text-center">
                    <div class="card-title">
                        <h3>Add Item</h3>
                    </div>
                </div>
                <div class="card-body">
                    <form  method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.name }}
                                <br>
                                {{ field }}
                            </div>
                        {% endfor %}
                        <button class="btn btn-primary " type="submit">Save</button>
                    </form> 
                </div> 
            </div>          
        </div>
    </div>
</div>


{% endblock %}

mysite/users/templates/users/login.html
{% extends 'food/base.html' %}
{% block body %}

    <div class="container">
        <div class="row mt-5">
            <div class="col-md-4 offset-md-4">
                <div class="card">
                    <div class="card-header text-white bg-info">
                        <div class="card-title text-center h3">Login</div>
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
                                     {{ field.name }}
                                     {{ field }}
                                </div>
                            {% endfor %}
                            <button class="btn btn-info" type="submit">Login</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

mysite/users/templates/users/logout.html
{% extends 'food/base.html' %}
{% block body %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header bg-info text-white text-center">
                    <div class="card-title">
                        <h1>You have been logged out!</h1>
                    </div>
                </div>
                <div class="card-body text-center">
                    <h5>Login to Continue!</h5>
                </div> 
            </div>          
        </div>
    </div>
</div>


{% endblock %}

   

mysite/users/templates/users/profile.html
{% extends 'food/base.html' %}
{% block body %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header bg-dark text-white text-center">
                    <div class="card-title">
                        <h1>profile</h1>
                    </div>
                </div>
                <div class="card-body">
                    <p>Username: <h4>{{ user.username }}</h4></p>
                    <p>Username: <h4>{{ user.email }}</h4></p>
                    <img src="{{ user.profile.image.url }}" alt="profile pic">
                </div> 
            </div>          
        </div>
    </div>
</div>


{% endblock %}

mysite/users/templates/users/register.html
{% extends 'food/base.html' %}
{% block body %}

    <div class="container">
        <div class="row mt-5">
            <div class="col-md-4 offset-md-4">
                <div class="card">
                    <div class="card-header text-white bg-info">
                        <div class="card-title text-center h3">Register</div>
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
                                     {{ field.name }}
                                     <br>
                                     {{ field }}
                                </div>
                            {% endfor %}
                            <button class="btn btn-info" type="submit">Sign up</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}